name: 🛠Техническая задача
description: Внутренняя задача по разработке, рефакторингу, настройке или техническому долгу.
title: "[TASK]: Краткое и точное описание задачи"
labels: ["task"] # Примеры внутренних меток
body:
  - type: markdown
    attributes:
      value: |
        ## Цель задачи
        *Четко опишите, зачем выполняется эта работа и какой результат ожидается.*

  - type: textarea
    id: requirements
    attributes:
      label: Требования и Детали
      description: Максимально детализируйте, что нужно сделать. Включите ссылки на документацию, схемы БД или другие связанные Issue.
      placeholder: |
        1. Реализовать новый метод API GET /api/v1/resource/status.
        2. Метод должен возвращать структуру: { "is_active": boolean, "last_ping": datetime }.
        3. Обновить ORM-модель `Resource` полем `last_ping`.
        4. Необходимое поле для авторизации: `API-Key`.
      render: markdown
    validations:
      required: true

  - type: input
    id: estimation
    attributes:
      label: Оценка времени (в часах или днях)
      description: Предварительная оценка времени, необходимого для выполнения задачи.
      placeholder: "4h"
    validations:
      required: false

  - type: input
    id: depends-on
    attributes:
      label: Зависимости (Depends On)
      description: Ссылки на другие задачи или PR, от которых зависит выполнение этой задачи.
      placeholder: "#123"
    validations:
      required: false